title: Matt Oestreich
author: Matt Oestreich
email: matthewpoestreich@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Matt Oestreich
show_excerpts: true # set to true to show excerpts on the homepage
# baseurl: /texture

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Matt Oestreich
  tagline: Technology. Development.
  date_format: "%b %-d, %Y"
  style: black
  showNav: true
  navigation:
    - title: About Me
      url: "/about"
    #- title: Resume
    #  url: "/resume"
  showPicker: false

  # generate social links in footer
  social_links:
    github:  oze4
    linkedIn: in/matt-oestreich-99251862
    stackoverflow: matty
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
  #- jekyll-feed
